### PR TITLE
Website overhaul

### PR DESCRIPTION
**Pull request by dexX7**
This pull request replaces the old website with a new design.

Note: currently there is PHP code for the price ticker, but GitHub pages doesn't support PHP, so it's disabled.

Live preview: http://bitwatch.co/omnilayer/

### CODE REVIEW

**Comment by msgilligan** [comment]
I think you might want to change *Videos* to *Video* (removing the `'` was a good idea, but I think it can also be used without the plural)

It would also be good to publish the latest modifications to a test URL so we can review it live. I mostly want to review the content, not the code.

**Comment by dexX7** [comment]
The idea is that there are more videos, e.g. Craig's talk about vAtomic. But I can change it of course.

The live preview is based on all commits I pushed here.

**Comment by zathras-crypto** [comment]
Love it :)

**Comment by achamely** [comment]
Definitely liking the update/improvements. The only thing left for me to address is the names under the pictures. I know you pulled them from github but they don't quite fit with the pics. I think we should go with  either just first names or preferred pseudonym

**Comment by dexX7** [comment]
@achamely: can you post a list with names, so I can update them?

**Comment by achamely** [comment]
@dexX7 
i'd say use: 
Adam, Craig, dexx (or your preference), Judith, Marv, Sean, Zathras (or his preference)

**Comment by dexX7** [comment]
Updated and uploaded new preview to http://bitwatch.co/omnilayer/.

**Comment by msgilligan** [comment]
I'm seeing a broken image to the left of *Testimonials*.

**Comment by dexX7** [comment]
Could have been a bad upload. I uploaded it again and I currently don't see a missing image.

**Comment by davidpbrown** [comment]
hmm.. "Could do better", springs to mind!

Below the sum of first impressions; fragmented frustration at the understated ambition relative to the potential of Omni; and a lack of time to polish it.. reflecting that at is stands it's a draft page that needs perhaps a couple of iterations still.

# Presentation
Light grey text on white, sucks and always will. There's currently some text there that is just too lite. It's a default that should always be changed; black on white is just a better default, if in doubt.

# The Menu
Choose wisely.. because the menu will disappear from sight! If you are having a fancy auto scroll menu, then surely it should float at the top.. otherwise it's a long scroll back to the top. Who is going to scroll all the way through the gaps for the content that is there?

Off target anchors at least when javascript is disabled http://bitwatch.co/omnilayer/#GetStarted needs a space on top the title [Get started] and then for [GitHub projects].

The target for Partners, is off target and looks weak without detail to back up why its included. Partners perhaps can be assumed unless significant and if they are, state it.

# Content
Where's the depth?.. [Blockchain based crowdfunding] looks like it should be a link to another page of content just about that.
I wonder instead of weekly updates you could spend time writing one page per topic for the medium term. Some generic that sells a particular point - the past and the future potential.

The video is a nice idea - post the narrative as text, why not?

The video production is not great, with annoying clatter of music and faux accented voice, where better would be a dev just talked to what he knows. Marketing polish stinks after a point; authentic quality, even unpolished is better sometimes - people looking for value and content they can trust; not an advert that they can't.

Don't include arrows to video2 that doesn't exist .. and that message the video is trying to convey, surely should be front and centre up top.

The big problem, is the [About] is not talking to anyone who doesn't know what Omni is for already. Imagine you are the other person who knows nothing and talk to them.

There's too much whitespace - [Built on top of the Bitcoin blockchain] doesn't look to be the same section of content as [Easily create custom currencies]; [Blockchain based crowdfunding]; [Trade peer-to-peer] - you could have those listed as bullet points that link to the paragraph below.

# Sell the idea
The visitor is left wondering too much about the question they arrived with, and not instead about new thoughts that you've suggested to them.

What is the ambition; what is the track record; what is the skill set of the devs.
What might Omni do in the future for John Doe?.. if he's an ambitious businessman with no tech understanding but a fk tonne of money to invest, why should he think more about Omni.. etc for all classes of random visitor.


The choice if this normal form of website template, which requires too much scrolling for too little content, does not scream cutting edge; so, the content of what you say needs to pack a punch - otherwise those who pass by will miss the point and you'll be preaching to the converted.

Selling even just an idea, is about creating excitement and cannot follow from assuming knowledge learned elsewhere.
If someone knows nothing about Omni or Bitcoin, would the website walk them through simple concepts and reasons to be excited?

Who is the audience and what product are you trying to sell?
Are you looking for new users; new investors; new developers?? Tell then each how to get involved and why they should be excited to.


"Bitcoin and blockchain technology's potential is only just becoming understood"
"Having the potential to create new currencies and tokens that are linked to real world assets could revolutionise the way our world works."

+Omni is an experienced team of developers; was one of the first choices for some of the earliest ICOs and has proven itself a secure and stable plarform eversince.
+Omni have provided one of the most stable platforms to [insert class of users], over a number of years.
+and have ambitions to provide capability that will allow you to: LIST THEM!.. if nothing new add the content from https://omniexplorer.info/features.aspx 

The opportunity available then to businesses in the future includes: x,y,z.

To partner with us at the exciting time contact: (tempt what you want to happen - be open and bold about your amibition - if you only want contact from a certain skillset then demand that.)

[Get started] elements - the icons at least need also to be links.. people more likely to click those than the text link below.

There's no reason that every element of content there should not link to even a small amount more depth to satisfy curiousity.
Most people on the planet do not understand what a web wallet is let alone a private key.

Typo at [Fully-validating desktop wllet]

Unfortunate you only have one "Testimonials" and that only suggesting "nice". This means nothing: "Having the original bitcoin RPC on top of the additional commands was exactly how it should be."

# Sell your strengths

Who are the devs.. there's literally zero detail and immediately below it suggesting "Meet the people who are working on improving the Omni Layer." A photo and a first name, ain't that!.. I'm left wondering that Marv looks like the bloke of Grand Designs=Kevin McCloud!.. and then not thinking about Omni!!

# Getting it right takes time but is worth it.

For those of us frustrated at the value of Omni, it would be good to see some effort put to promoting the idea and reasons that others should take Omni seriously. Part of the reason perhaps for the price, is the way in which Omni does not suggest itself clearly enough for noobs to become engaged. Surely the point of a website it to raise the profile of Omni.

Again then I'd suggest you consider which audiences you are communicating to and think carefully what they need to know and how they you are communicating that - the sum total of which needs prioritizing.. which message to which audience is most important?

**Comment by davidpbrown** [comment]
If not already included perhaps link to 

Dex 2.0 getting Started Guide = https://blog.omni.foundation/2016/03/16/omnidex-getting-started/

Issued Assets = https://www.omniwallet.org/explorer/assets - though that still defaults badly without javascript enabled.

**Comment by davidpbrown** [comment]
oh and final thought.. languages.. why only English?.. perhaps include a simple translation of the one page into a few international languages to match Omni's ambition of being omnipresent??

**Comment by dexX7** [comment]
Hi @davidpbrown,

thanks for your feedback! Please note, this pull request primarily updates the design and replaces the old website as it. I would really love to have a lot more content, but this is unfortunately something we don't have ready.

However, I picked up a few of your suggestions:

- updated navigation and replaced "Partners" with "Testimonials"
- added two more YouTube videos
- fixed typo
- added links to OW, OE and the MetaDEx guide in the feature descriptions

**Comment by msgilligan** [comment]
Looking good!

 I still think **Video** should not end with an `s`. In the  the context of the web page I think the usage is as an [uncountable noun](https://www.wordhippo.com/what-is/the-plural-of/video.html). An argument could be made either way, but I think **Video** sounds better in this context.

**Pull request merged**
